# Generated by Django 2.1.7 on 2019-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todoitem_due_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='done',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
